version: '3'
services:
  hf-app-fastapi:
    build:
      context: .
    volumes:
    # only filechanges in .app trigger app live-reload
      - ./:/app
      - /app/tests # needed to exclude app reload
      - /.git # needed to exclude app reload
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      BACKEND_CORS_ORIGINS: '["http://localhost", "http://localhost:8000"]'