version: '3'
services:
  hf-app-fastapi:
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      BACKEND_CORS_ORIGINS: '["http://localhost", "http://localhost:8000"]'